version: "3"

services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    volumes:
      - /Users/nakama/sonar-conf:/opt/sonarqube/conf
  
  sonarqube2:
    container_name: sonarqube2
    image: sonarqube
    ports:
      - "9090:9090"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.web.port=9090
    volumes:
      - /Users/nakama/sonar-conf:/opt/sonarqube/conf
    

  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
  

networks:
  sonarnet:
